rows:
  - date: 2020-04-01
    title: The journey begins
    body: Moved into my first house and discovered my love for gardening. Quickly began renovations on the front flower bed and retaining wall.
    tag: new roots
  - date: 2022-08-20
    title: Non-stop BLTs
    body: So many tomatoes this year! It was challenging trying to use and give away everything before they went bad.
    tag: bountiful harvest
  - date: 2025-09-16
    title: Backyard Renovations Complete
    body: The renovations have completed including new retaining wall, shed, and concrete pads.
    tag: renewal
  - date: 2026-06-01
    title: Pergola Built
    body: Family help built a new pergola to enjoy the backyard gardens with a little shade.
    tag: family <3
