groups:
  - heading: Main Languages
    items:
      - Ruby
      - JavaScript
      - SQL
      - Bash
      - Python
  - heading: Frameworks & Tools
    items:
      - Rails
      - Hotwire (Turbo, Stimulus)
      - Tailwind
      - DaisyUI
      - Vue
  - heading: Data & Infra
    items:
      - PostgreSQL
      - mySQL
      - Redis
      - Docker
      - GitHub Actions
      - AWS
      - API Gateway
  - heading: Garden tools
    items:
      - Trowel
      - Pruners
      - Gloves
      - Lots of Patience
