groups:
  - heading: Favorite Languages
    items:
      - Ruby
      - JavaScript
      - SQL
      - Bash
      - Python
  - heading: Favorite Frameworks
    items:
      - Rails
      - Hotwire (Turbo + Stimulus)
      - Tailwind / daisyUI
      - Vue
      - Sidekiq
  - heading: Data & Infra
    items:
      - PostgreSQL
      - mySQL
      - Redis
      - Docker
      - GitHub Actions
      - AWS
  - heading: Garden tools
    items:
      - Trowel
      - Compost
      - Patience
      - A very large watering can
