// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TocController from "./toc_controller"
application.register("toc", TocController)

import TypewriterController from "./typewriter_controller"
application.register("typewriter", TypewriterController)
