// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CloudflareTurnstileController from "./cloudflare_turnstile_controller"
application.register("cloudflare-turnstile", CloudflareTurnstileController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TypewriterController from "./typewriter_controller"
application.register("typewriter", TypewriterController)
