# Operational tasks for the wedding invitations. The roster itself is maintained
# in db/seeds.rb and applied with `bin/rails db:seed` — nothing here writes guests.
namespace :wedding do
  # Tokens are generated by the model, so this is the only way to discover a
  # guest's invitation URL. This is the task used to actually send invitations.
  desc "Print each guest's invitation URL, grouped by party"
  task links: :environment do
    each_group do |group, guests|
      puts "Group #{group}"
      guests.each { |guest| puts "  #{guest.name.ljust(24)} #{invitation_url(guest)}" }
      puts
    end
  end

  desc "Print a yes/no/unknown RSVP tally, grouped by party"
  task status: :environment do
    each_group do |group, guests|
      counts = guests.group_by(&:status).transform_values(&:size)
      puts "Group #{group} — #{Guest.statuses.keys.map { |s| "#{s}: #{counts.fetch(s, 0)}" }.join('  ')}"
      guests.each { |guest| puts "  #{guest.status.ljust(8)} #{guest.name}" }
      puts
    end

    totals = Guest.group(:status).count
    puts "All guests (#{Guest.count}) — #{Guest.statuses.keys.map { |s| "#{s}: #{totals.fetch(s, 0)}" }.join('  ')}"
  end

  # Seeding never deletes, so a guest removed from db/seeds.rb keeps their row
  # and their working invitation link. This reports that drift; removing them is
  # a deliberate manual act.
  desc "List guests in the database that db/seeds.rb no longer mentions"
  task orphans: :environment do
    puts "Applying the roster from db/seeds.rb first (idempotent)..."
    Rails.application.load_seed

    rostered = WeddingRoster.groups.flat_map { |group, names| names.map { |name| [ group, name ] } }.to_set
    orphans  = Guest.ordered.reject { |guest| rostered.include?([ guest.group, guest.name ]) }

    if orphans.empty?
      puts "No orphans — every guest in the database is in the roster."
    else
      puts "\n#{orphans.size} guest(s) in the database but not in db/seeds.rb:"
      orphans.each { |guest| puts "  Group #{guest.group} / #{guest.name} (#{guest.status}) — #{invitation_url(guest)}" }
      puts "\nThese still have working invitation links. Delete them in the console if that's intended."
    end
  end

  desc "Generate one QR code PNG per party, encoding that party's invitation URL"
  task qrcodes: :environment do
    output_dir = Rails.root.join("tmp", "qrcodes")
    FileUtils.mkdir_p(output_dir)

    each_group do |group, guests|
      url = invitation_url(guests.first)
      png = RQRCode::QRCode.new(url).as_png(size: 300, fill: "white", color: "black")

      # The group number alone would name these 1.png..32.png, which is unusable
      # when you're matching a printed code to a party. Zero-padded so they sort,
      # and carrying the first guest's name so the file says who it's for.
      path = output_dir.join("group-#{group.to_s.rjust(2, '0')}-#{guests.first.name.parameterize}.png")
      File.binwrite(path, png.to_s)

      puts "Group #{group.to_s.ljust(4)} #{path}"
    end
  end

  def each_group(&block)
    Guest.ordered.group_by(&:group).each(&block)
  end

  # Defaults to the production host so copied links are sendable as-is;
  # override for local checks with HOST=http://localhost:3000.
  def invitation_url(guest)
    host = ENV.fetch("HOST", "https://ncurwen.dev")
    Rails.application.routes.url_helpers.invitations_url(token: guest.token, host: host)
  end
end
