// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import CopyComponentController from "./copy_component_controller"
application.register("copy-component", CopyComponentController)

import FlashComponentController from "./flash_component_controller"
application.register("flash-component", FlashComponentController)

import PhotoGalleryFilterComponentController from "./photo_gallery_filter_component_controller"
application.register("photo-gallery-filter-component", PhotoGalleryFilterComponentController)

import PhotoGalleryLightboxComponentController from "./photo_gallery_lightbox_component_controller"
application.register("photo-gallery-lightbox-component", PhotoGalleryLightboxComponentController)

import TableOfContentsComponentController from "./table_of_contents_component_controller"
application.register("table-of-contents-component", TableOfContentsComponentController)

import ThemeToggleComponentController from "./theme_toggle_component_controller"
application.register("theme-toggle-component", ThemeToggleComponentController)

import Wedding__CountdownComponentController from "./wedding/countdown_component_controller"
application.register("wedding--countdown-component", Wedding__CountdownComponentController)

import Wedding__RsvpControlsComponentController from "./wedding/rsvp_controls_component_controller"
application.register("wedding--rsvp-controls-component", Wedding__RsvpControlsComponentController)
