entries:
  - date: 2020-04-01
    title: The journey begins
    body: Moved into my first house and discovered my love for gardening. Quickly began renovations on the front flower bed and retaining wall.
    tag: new roots
