# The wedding guest list. This file is the roster's source of truth: add or edit
# groups below and run `bin/rails db:seed` to apply them.
#
# Safe to run at any point, in any environment:
#   * `find_or_create_by!` only assigns on create, so re-seeding never resets a
#     guest's RSVP or churns the token in their invitation URL.
#   * Nothing is ever deleted. Removing a name here leaves the row alone —
#     `bin/rails wedding:orphans` reports the drift so removal stays deliberate.
#
# Tokens are generated by the model, so there is nothing to fill in by hand.
# Run `bin/rails wedding:links` to get each guest's invitation URL.
#
# The key is an opaque group number, not a name: it exists only to link a party
# together so one person's link can answer for all of them, and it is never shown
# to a guest. Number a new group with the next integer; don't renumber existing
# ones. A group number is part of a guest's identity here, so renumbering someone
# or moving them between groups creates a new row with a new link rather than
# editing the old one. `wedding:orphans` will surface the leftover.
#
# A plus-one gets their own row — every seat needs one to be RSVP-able — named
# for whoever it belongs to, since the shared guest list shows these names.
module WeddingRoster
  # Deliberately a method rather than a constant: db/seeds.rb gets loaded more
  # than once (tests, wedding:orphans), and re-assigning a constant warns —
  # which test_helper.rb's minitest/error_on_warning turns into a failure.
  def self.groups
    {
      1  => [ "Hank", "Jean" ],
      2  => [ "Marc", "Kristiaan", "Elyse", "Harrison" ],
      3  => [ "Louk", "Louk's Guest" ],
      4  => [ "Kasey", "Nazar", "Landon" ],
      5  => [ "Mom", "Dad" ],
      6  => [ "Eric", "Jay" ],
      7  => [ "Amma", "Thatha", "Asith" ],
      8  => [ "Anusha", "Karan" ],
      9  => [ "Ayya", "Mehreen" ],
      10 => [ "Prasad", "Renu" ],
      11 => [ "Sampath", "Sampath's Guest" ],
      12 => [ "Sukhee", "Sai", "Oshen" ],
      13 => [ "Preethi", "Jagath" ],
      14 => [ "Isuri", "Isuri's Guest" ],
      15 => [ "Marvan", "Kate" ],
      16 => [ "Jesse", "Michelle", "Ryker", "Millie" ],
      17 => [ "Dylan", "Dylan's Guest" ],
      18 => [ "Jamie", "Rachel" ],
      19 => [ "Tayler", "Kara" ],
      20 => [ "Matt", "Matt's Guest" ],
      21 => [ "Derek", "Kat" ],
      22 => [ "Alex", "JP" ],
      23 => [ "Christine", "Luke" ],
      24 => [ "Robyn", "Robyn's Guest" ],
      25 => [ "Jay", "Angie" ],
      26 => [ "Jen", "Davey" ],
      27 => [ "Paul", "Nancy" ],
      28 => [ "Matt", "Emily" ],
      29 => [ "Rob", "Jocelyn" ],
      30 => [ "Bert", "Jess" ],
      31 => [ "Wes", "Wes's Guest" ],
      32 => [ "Cory", "Ruksi" ]
    }
  end

  def self.sync!
    groups.sum do |group, names|
      names.count { |name| Guest.find_or_create_by!(name: name, group: group).previously_new_record? }
    end
  end
end

created = WeddingRoster.sync!
puts "Wedding roster: #{Guest.count} guests across #{Guest.distinct.count(:group)} groups (#{created} created this run)."
