# The wedding guest list. This file is the roster's source of truth: add or edit
# households below and run `bin/rails db:seed` to apply them.
#
# Safe to run at any point, in any environment:
#   * `find_or_create_by!` only assigns on create, so re-seeding never resets a
#     guest's RSVP or churns the token in their invitation URL.
#   * Nothing is ever deleted. Removing a name here leaves the row alone —
#     `bin/rails wedding:orphans` reports the drift so removal stays deliberate.
#
# Tokens are generated by the model, so there is nothing to fill in by hand.
# Run `bin/rails wedding:links` to get each guest's invitation URL.
#
# Note: a household key is part of a guest's identity here, so renaming a person
# or moving them between households creates a new row with a new link rather
# than editing the old one. `wedding:orphans` will surface the leftover.
module WeddingRoster
  # Deliberately a method rather than a constant: db/seeds.rb gets loaded more
  # than once (tests, wedding:orphans), and re-assigning a constant warns —
  # which test_helper.rb's minitest/error_on_warning turns into a failure.
  def self.households
    {
      "The Placeholder Family" => [
        "Alex Placeholder",
        "Sam Placeholder",
        "Robin Placeholder"
      ],
      "The Example Household" => [
        "Jordan Example",
        "Casey Example"
      ],
      "Placeholder College Friends" => [
        "Riley Sample",
        "Morgan Sample"
      ],
      "Work Placeholders" => [
        "Avery Placeholder"
      ]
    }
  end

  def self.sync!
    households.sum do |group, names|
      names.count { |name| Guest.find_or_create_by!(name: name, group: group).previously_new_record? }
    end
  end
end

created = WeddingRoster.sync!
puts "Wedding roster: #{Guest.count} guests across #{Guest.distinct.count(:group)} households (#{created} created this run)."
